const countriesCodes = [
  {
    countryName: "Afghanistan",
    alpha2: "AF",
    alpha3: "AFG",
    numericContryCode: "004",
    currencyName: "Afghani",
    defaultNumerucCurrencyCode: "971",
    alphaCurrencyCode: "AFN",
    numericCurrencyCode: "971",
    minorUnit: "2",
  },
  {
    countryName: "Albania",
    alpha2: "AL",
    alpha3: "ALB",
    numericContryCode: "008",
    currencyName: "Lek",
    defaultNumerucCurrencyCode: "008",
    alphaCurrencyCode: "ALL",
    numericCurrencyCode: "008",
    minorUnit: "2",
  },

  {
    countryName: "Algeria",
    alpha2: "DZ",
    alpha3: "DZA",
    numericContryCode: "012",
    currencyName: "Algerian Dinar",
    defaultNumerucCurrencyCode: "012",
    alphaCurrencyCode: "DZD",
    numericCurrencyCode: "012",
    minorUnit: "2",
  },

  {
    countryName: "American Samoa",
    alpha2: "AS",
    alpha3: "ASM",
    numericContryCode: "016",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Andorra",
    alpha2: "AD",
    alpha3: "AND",
    numericContryCode: "020",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Angola",
    alpha2: "AO",
    alpha3: "AGO",
    numericContryCode: "024",
    currencyName: "Kwanza",
    defaultNumerucCurrencyCode: "973",
    alphaCurrencyCode: "AOA",
    numericCurrencyCode: "973",
    minorUnit: "2",
  },

  {
    countryName: "Anguilla",
    alpha2: "AI",
    alpha3: "AIA",
    numericContryCode: "660",
    currencyName: "E. Caribbean Dollar",
    defaultNumerucCurrencyCode: "951",
    alphaCurrencyCode: "XCD",
    numericCurrencyCode: "951",
    minorUnit: "2",
  },

  {
    countryName: "Antigua and Barbuda",
    alpha2: "AG",
    alpha3: "ATG",
    numericContryCode: "028",
    currencyName: "E. Caribbean Dollar",
    defaultNumerucCurrencyCode: "951",
    alphaCurrencyCode: "XCD",
    numericCurrencyCode: "951",
    minorUnit: "2",
  },

  {
    countryName: "Argentina",
    alpha2: "AR",
    alpha3: "ARG",
    numericContryCode: "032",
    currencyName: "Argentine Peso",
    defaultNumerucCurrencyCode: "032",
    alphaCurrencyCode: "ARS",
    numericCurrencyCode: "032",
    minorUnit: "2",
  },

  {
    countryName: "Armenia",
    alpha2: "AM",
    alpha3: "ARM",
    numericContryCode: "051",
    currencyName: "Armenian Dram",
    defaultNumerucCurrencyCode: "051",
    alphaCurrencyCode: "AMD",
    numericCurrencyCode: "051",
    minorUnit: "2",
  },

  {
    countryName: "Aruba",
    alpha2: "AW",
    alpha3: "ABW",
    numericContryCode: "533",
    currencyName: "Aruban Guilder",
    defaultNumerucCurrencyCode: "533",
    alphaCurrencyCode: "AWG",
    numericCurrencyCode: "533",
    minorUnit: "2",
  },

  {
    countryName: "Australia",
    alpha2: "AU",
    alpha3: "AUS",
    numericContryCode: "036",
    currencyName: "Australian Dollar",
    defaultNumerucCurrencyCode: "036",
    alphaCurrencyCode: "AUD",
    numericCurrencyCode: "036",
    minorUnit: "2",
  },

  {
    countryName: "Austria",
    alpha2: "AT",
    alpha3: "AUT",
    numericContryCode: "040",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Azerbaijan",
    alpha2: "AZ",
    alpha3: "AZE",
    numericContryCode: "031",
    currencyName: "Azerbaijan Manat",
    defaultNumerucCurrencyCode: "944",
    alphaCurrencyCode: "AZN",
    numericCurrencyCode: "944",
    minorUnit: "2",
  },

  {
    countryName: "BAhamas",
    alpha2: "BS",
    alpha3: "BHS",
    numericContryCode: "044",
    currencyName: "Bahamian Dollar",
    defaultNumerucCurrencyCode: "044",
    alphaCurrencyCode: "BSD",
    numericCurrencyCode: "044",
    minorUnit: "2",
  },

  {
    countryName: "Bahrain",
    alpha2: "BH",
    alpha3: "BHR",
    numericContryCode: "048",
    currencyName: "Bahraini Dinar",
    defaultNumerucCurrencyCode: "048",
    alphaCurrencyCode: "BHD",
    numericCurrencyCode: "048",
    minorUnit: "2",
  },

  {
    countryName: "Bangladesh",
    alpha2: "BD",
    alpha3: "BGD",
    numericContryCode: "050",
    currencyName: "Taka",
    defaultNumerucCurrencyCode: "050",
    alphaCurrencyCode: "BDT",
    numericCurrencyCode: "050",
    minorUnit: "2",
  },

  {
    countryName: "Barbados",
    alpha2: "BB",
    alpha3: "BRB",
    numericContryCode: "052",
    currencyName: "Barbados Dollar",
    defaultNumerucCurrencyCode: "052",
    alphaCurrencyCode: "BBD",
    numericCurrencyCode: "052",
    minorUnit: "2",
  },

  {
    countryName: "Belarus",
    alpha2: "BY",
    alpha3: "BLR",
    numericContryCode: "112",
    currencyName: "Belarusian Ruble",
    defaultNumerucCurrencyCode: "974",
    alphaCurrencyCode: "BYR",
    numericCurrencyCode: "974",
    minorUnit: "0",
  },

  {
    countryName: "Belgium",
    alpha2: "BE",
    alpha3: "BEL",
    numericContryCode: "056",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Belize",
    alpha2: "BZ",
    alpha3: "BLZ",
    numericContryCode: "084",
    currencyName: "Belize Dollar",
    defaultNumerucCurrencyCode: "084",
    alphaCurrencyCode: "BZD",
    numericCurrencyCode: "084",
    minorUnit: "2",
  },

  {
    countryName: "Benin",
    alpha2: "BJ",
    alpha3: "BEN",
    numericContryCode: "204",
    currencyName: "CFA Franc BCEAO",
    defaultNumerucCurrencyCode: "952",
    alphaCurrencyCode: "XOF",
    numericCurrencyCode: "952",
    minorUnit: "0",
  },

  {
    countryName: "Bermuda",
    alpha2: "BM",
    alpha3: "BMU",
    numericContryCode: "060",
    currencyName: "Bermudian Dollar",
    defaultNumerucCurrencyCode: "060",
    alphaCurrencyCode: "BMD",
    numericCurrencyCode: "060",
    minorUnit: "2",
  },

  {
    countryName: "Bhutan",
    alpha2: "BT",
    alpha3: "BTN",
    numericContryCode: "064",
    currencyName: "Indian Rupee<br>Bhutan Ngultrum",
    defaultNumerucCurrencyCode: "356<br>064",
    alphaCurrencyCode: "INR<br>BTN",
    numericCurrencyCode: "356<br>064",
    minorUnit: "2<br>2",
  },

  {
    countryName: "Bolivia",
    alpha2: "BO",
    alpha3: "BOL",
    numericContryCode: "068",
    currencyName: "Boliviano",
    defaultNumerucCurrencyCode: "068",
    alphaCurrencyCode: "BOB",
    numericCurrencyCode: "068",
    minorUnit: "2",
  },

  {
    countryName: "Bonaire,\nSint Eustatius,\nand Saba",
    alpha2: "BQ",
    alpha3: "BES",
    numericContryCode: "535",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Bosnia and Herzegovina",
    alpha2: "BA",
    alpha3: "BIH",
    numericContryCode: "070",
    currencyName: "Convertible Mark",
    defaultNumerucCurrencyCode: "977",
    alphaCurrencyCode: "BAM",
    numericCurrencyCode: "977",
    minorUnit: "2",
  },

  {
    countryName: "Botswana",
    alpha2: "BW",
    alpha3: "BWA",
    numericContryCode: "072",
    currencyName: "Pula",
    defaultNumerucCurrencyCode: "072",
    alphaCurrencyCode: "BWP",
    numericCurrencyCode: "072",
    minorUnit: "2",
  },

  {
    countryName: "Bouvet Is.",
    alpha2: "BV",
    alpha3: "BVT",
    numericContryCode: "074",
    currencyName: "Norwegian Krone",
    defaultNumerucCurrencyCode: "578",
    alphaCurrencyCode: "NOK",
    numericCurrencyCode: "578",
    minorUnit: "2",
  },

  {
    countryName: "Brazil",
    alpha2: "BR",
    alpha3: "BRA",
    numericContryCode: "076",
    currencyName: "Brazilian Real",
    defaultNumerucCurrencyCode: "076",
    alphaCurrencyCode: "BRL",
    numericCurrencyCode: "986",
    minorUnit: "2",
  },

  {
    countryName: "British Indian Ocean Territory",
    alpha2: "IO",
    alpha3: "IOT",
    numericContryCode: "086",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "British Virgin Is",
    alpha2: "VG",
    alpha3: "VGB",
    numericContryCode: "092",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "X840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Brunei Darussalam",
    alpha2: "BN",
    alpha3: "BRN",
    numericContryCode: "096",
    currencyName: "Brunei Dollar",
    defaultNumerucCurrencyCode: "096",
    alphaCurrencyCode: "BND",
    numericCurrencyCode: "096",
    minorUnit: "2",
  },

  {
    countryName: "Bulgaria",
    alpha2: "BG",
    alpha3: "BGR",
    numericContryCode: "100",
    currencyName: "Bulgarian Lev",
    defaultNumerucCurrencyCode: "975",
    alphaCurrencyCode: "BGN",
    numericCurrencyCode: "975",
    minorUnit: "2",
  },

  {
    countryName: "Burkina Faso",
    alpha2: "BF",
    alpha3: "BFA",
    numericContryCode: "854",
    currencyName: "CFA Franc BCEAO",
    defaultNumerucCurrencyCode: "952",
    alphaCurrencyCode: "XOF",
    numericCurrencyCode: "952",
    minorUnit: "0",
  },

  {
    countryName: "Burundi",
    alpha2: "BI",
    alpha3: "BDI",
    numericContryCode: "108",
    currencyName: "Burundi Franc",
    defaultNumerucCurrencyCode: "108",
    alphaCurrencyCode: "BIF",
    numericCurrencyCode: "108",
    minorUnit: "0",
  },

  {
    countryName: "Cambodia",
    alpha2: "KH",
    alpha3: "KHM",
    numericContryCode: "116",
    currencyName: "Riel",
    defaultNumerucCurrencyCode: "116",
    alphaCurrencyCode: "KHR",
    numericCurrencyCode: "116",
    minorUnit: "2",
  },

  {
    countryName: "Cameroon, United Republic of",
    alpha2: "CM",
    alpha3: "CMR",
    numericContryCode: "120",
    currencyName: "CFA Franc BEAC",
    defaultNumerucCurrencyCode: "950",
    alphaCurrencyCode: "XAF",
    numericCurrencyCode: "950",
    minorUnit: "0",
  },

  {
    countryName: "Canada",
    alpha2: "CA",
    alpha3: "CAN",
    numericContryCode: "124",
    currencyName: "Canadian Dollar",
    defaultNumerucCurrencyCode: "124",
    alphaCurrencyCode: "CAD",
    numericCurrencyCode: "124",
    minorUnit: "2",
  },

  {
    countryName: "Cayman Is.",
    alpha2: "KY",
    alpha3: "CYM",
    numericContryCode: "136",
    currencyName: "Cayman Is. Dollar",
    defaultNumerucCurrencyCode: "136",
    alphaCurrencyCode: "KYD",
    numericCurrencyCode: "136",
    minorUnit: "2",
  },

  {
    countryName: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    numericContryCode: "140",
    currencyName: "CFA Franc BEAC",
    defaultNumerucCurrencyCode: "950",
    alphaCurrencyCode: "XAF",
    numericCurrencyCode: "950",
    minorUnit: "0",
  },

  {
    countryName: "Chad",
    alpha2: "TD",
    alpha3: "TCD",
    numericContryCode: "148",
    currencyName: "CFA Franc BEAC",
    defaultNumerucCurrencyCode: "950",
    alphaCurrencyCode: "XAF",
    numericCurrencyCode: "950",
    minorUnit: "0",
  },

  {
    countryName: "Chile",
    alpha2: "CL",
    alpha3: "TCD",
    numericContryCode: "152",
    currencyName: "Chilean Peso",
    defaultNumerucCurrencyCode: "152",
    alphaCurrencyCode: "CLP",
    numericCurrencyCode: "152",
    minorUnit: "2",
  },

  {
    countryName: "China",
    alpha2: "CN",
    alpha3: "CHN",
    numericContryCode: "156",
    currencyName: "Yuan Renminbi",
    defaultNumerucCurrencyCode: "156",
    alphaCurrencyCode: "CNY",
    numericCurrencyCode: "156",
    minorUnit: "2",
  },

  {
    countryName: "Christmas Is.",
    alpha2: "CX",
    alpha3: "CXR",
    numericContryCode: "162",
    currencyName: "Australian Dollar",
    defaultNumerucCurrencyCode: "036",
    alphaCurrencyCode: "AUD",
    numericCurrencyCode: "036",
    minorUnit: "2",
  },

  {
    countryName: "Cocos (Keeling) Is.",
    alpha2: "CC",
    alpha3: "CCK",
    numericContryCode: "166",
    currencyName: "Australian Dollar",
    defaultNumerucCurrencyCode: "036",
    alphaCurrencyCode: "AUD",
    numericCurrencyCode: "036",
    minorUnit: "2",
  },

  {
    countryName: "Colombia",
    alpha2: "CO",
    alpha3: "COL",
    numericContryCode: "170",
    currencyName: "Colombian Peso",
    defaultNumerucCurrencyCode: "170",
    alphaCurrencyCode: "COP",
    numericCurrencyCode: "170",
    minorUnit: "2",
  },

  {
    countryName: "Comoros",
    alpha2: "KM",
    alpha3: "COM",
    numericContryCode: "174",
    currencyName: "Comoro Franc",
    defaultNumerucCurrencyCode: "174",
    alphaCurrencyCode: "KMF",
    numericCurrencyCode: "174",
    minorUnit: "0",
  },

  {
    countryName: "Congo",
    alpha2: "CG",
    alpha3: "COG",
    numericContryCode: "178",
    currencyName: "CFA Franc BEAC",
    defaultNumerucCurrencyCode: "950",
    alphaCurrencyCode: "XAF",
    numericCurrencyCode: "950",
    minorUnit: "0",
  },

  {
    countryName: "Cook Is.",
    alpha2: "CK",
    alpha3: "COK",
    numericContryCode: "184",
    currencyName: "New Zealand Dollar",
    defaultNumerucCurrencyCode: "554",
    alphaCurrencyCode: "NZD",
    numericCurrencyCode: "554",
    minorUnit: "2",
  },

  {
    countryName: "Costa Rica",
    alpha2: "CR",
    alpha3: "CRI",
    numericContryCode: "188",
    currencyName: "Costa Rican Colon",
    defaultNumerucCurrencyCode: "188",
    alphaCurrencyCode: "CRC",
    numericCurrencyCode: "188",
    minorUnit: "2",
  },

  {
    countryName: "Cote d'Ivoire (Ivory Coast)",
    alpha2: "CI",
    alpha3: "CIV",
    numericContryCode: "384",
    currencyName: "CFA Franc BCEAO",
    defaultNumerucCurrencyCode: "952",
    alphaCurrencyCode: "XOF",
    numericCurrencyCode: "952",
    minorUnit: "0",
  },

  {
    countryName: "Croatia",
    alpha2: "HR",
    alpha3: "HRV",
    numericContryCode: "191",
    currencyName: "Croatian Kuna",
    defaultNumerucCurrencyCode: "191",
    alphaCurrencyCode: "HRK",
    numericCurrencyCode: "191",
    minorUnit: "2",
  },

  {
    countryName: "Cuba",
    alpha2: "CU",
    alpha3: "CUW",
    numericContryCode: "192",
    currencyName: "Cuban Peso",
    defaultNumerucCurrencyCode: "192",
    alphaCurrencyCode: "CUP",
    numericCurrencyCode: "192",
    minorUnit: "2",
  },

  {
    countryName: "Curacao",
    alpha2: "CW",
    alpha3: "CUW",
    numericContryCode: "531",
    currencyName: "Netherlands Antillean Guilder",
    defaultNumerucCurrencyCode: "532",
    alphaCurrencyCode: "ANG",
    numericCurrencyCode: "532",
    minorUnit: "2",
  },

  {
    countryName: "Cyprus",
    alpha2: "CY",
    alpha3: "CYP",
    numericContryCode: "196",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Czech Republic",
    alpha2: "CZ",
    alpha3: "CZE",
    numericContryCode: "203",
    currencyName: "Czech Koruna",
    defaultNumerucCurrencyCode: "203",
    alphaCurrencyCode: "CZK",
    numericCurrencyCode: "203",
    minorUnit: "2",
  },

  {
    countryName: "Democratic Republic of the Congo",
    alpha2: "CD",
    alpha3: "COD",
    numericContryCode: "180",
    currencyName: "Franc Congolais",
    defaultNumerucCurrencyCode: "976",
    alphaCurrencyCode: "CDF",
    numericCurrencyCode: "976",
    minorUnit: "2",
  },

  {
    countryName: "Denmark",
    alpha2: "DK",
    alpha3: "DNK",
    numericContryCode: "208",
    currencyName: "Danish Krone",
    defaultNumerucCurrencyCode: "208",
    alphaCurrencyCode: "DKK",
    numericCurrencyCode: "208",
    minorUnit: "2",
  },

  {
    countryName: "Djibouti",
    alpha2: "DJ",
    alpha3: "DJI",
    numericContryCode: "262",
    currencyName: "Djibouti Franc",
    defaultNumerucCurrencyCode: "262",
    alphaCurrencyCode: "DJF",
    numericCurrencyCode: "262",
    minorUnit: "0",
  },

  {
    countryName: "Dominica",
    alpha2: "DM",
    alpha3: "DMA",
    numericContryCode: "212",
    currencyName: "E. Caribbean Dollar",
    defaultNumerucCurrencyCode: "951",
    alphaCurrencyCode: "XCD",
    numericCurrencyCode: "951",
    minorUnit: "2",
  },

  {
    countryName: "Dominican Rep.",
    alpha2: "DO",
    alpha3: "DOM",
    numericContryCode: "214",
    currencyName: "Dominican Peso",
    defaultNumerucCurrencyCode: "214",
    alphaCurrencyCode: "DOP",
    numericCurrencyCode: "214",
    minorUnit: "2",
  },

  {
    countryName: "Ecuador",
    alpha2: "EC",
    alpha3: "ECU",
    numericContryCode: "218",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Egypt",
    alpha2: "EG",
    alpha3: "EGY",
    numericContryCode: "818",
    currencyName: "Egyptian Pound",
    defaultNumerucCurrencyCode: "818",
    alphaCurrencyCode: "EGP",
    numericCurrencyCode: "818",
    minorUnit: "2",
  },

  {
    countryName: "El Salvador",
    alpha2: "SV",
    alpha3: "SLV",
    numericContryCode: "222",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Equatorial Guinea",
    alpha2: "GQ",
    alpha3: "GNQ",
    numericContryCode: "226",
    currencyName: "CFA Franc BEAC",
    defaultNumerucCurrencyCode: "950",
    alphaCurrencyCode: "XAF",
    numericCurrencyCode: "950",
    minorUnit: "0",
  },

  {
    countryName: "Eritrea",
    alpha2: "ER",
    alpha3: "ERI",
    numericContryCode: "232",
    currencyName: "Eritrean Nakfa",
    defaultNumerucCurrencyCode: "232",
    alphaCurrencyCode: "ERN",
    numericCurrencyCode: "232",
    minorUnit: "2",
  },

  {
    countryName: "Estonia",
    alpha2: "EE",
    alpha3: "EST",
    numericContryCode: "233",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Ethiopia",
    alpha2: "ET",
    alpha3: "ETH",
    numericContryCode: "231",
    currencyName: "Ethiopian Birr",
    defaultNumerucCurrencyCode: "230",
    alphaCurrencyCode: "ETB",
    numericCurrencyCode: "230",
    minorUnit: "2",
  },

  {
    countryName: "European Union",
    alpha2: "n/a",
    alpha3: "n/a",
    numericContryCode: "n/a",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Faroe Is.",
    alpha2: "FO",
    alpha3: "FRO",
    numericContryCode: "234",
    currencyName: "Danish Krone",
    defaultNumerucCurrencyCode: "208",
    alphaCurrencyCode: "DKK",
    numericCurrencyCode: "208",
    minorUnit: "2",
  },

  {
    countryName: "Falkland Is. (Malvinas)",
    alpha2: "FK",
    alpha3: "FLK",
    numericContryCode: "238",
    currencyName: "Falkland Is. Pound",
    defaultNumerucCurrencyCode: "238",
    alphaCurrencyCode: "FKP",
    numericCurrencyCode: "238",
    minorUnit: "2",
  },

  {
    countryName: "Fiji",
    alpha2: "FJ",
    alpha3: "FJI",
    numericContryCode: "242",
    currencyName: "Fiji Dollar",
    defaultNumerucCurrencyCode: "242",
    alphaCurrencyCode: "FJD",
    numericCurrencyCode: "242",
    minorUnit: "2",
  },

  {
    countryName: "Finland",
    alpha2: "FI",
    alpha3: "FIN",
    numericContryCode: "246",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "France",
    alpha2: "FR",
    alpha3: "FRA",
    numericContryCode: "250",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "France, Metropolitan",
    alpha2: "FX",
    alpha3: "FXX",
    numericContryCode: "249",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "French Guiana",
    alpha2: "GF",
    alpha3: "GUF",
    numericContryCode: "254",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "French Polynesia",
    alpha2: "PF",
    alpha3: "PYF",
    numericContryCode: "258",
    currencyName: "CFP Franc",
    defaultNumerucCurrencyCode: "953",
    alphaCurrencyCode: "XPF",
    numericCurrencyCode: "953",
    minorUnit: "0",
  },

  {
    countryName: "French Southern Territory",
    alpha2: "TF",
    alpha3: "ATF",
    numericContryCode: "260",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "Euro",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Gabon",
    alpha2: "GA",
    alpha3: "GAB",
    numericContryCode: "266",
    currencyName: "CFA Franc BEAC",
    defaultNumerucCurrencyCode: "950",
    alphaCurrencyCode: "XAF",
    numericCurrencyCode: "950",
    minorUnit: "0",
  },

  {
    countryName: "Gambia",
    alpha2: "GA",
    alpha3: "GAB",
    numericContryCode: "266",
    currencyName: "Dalasi",
    defaultNumerucCurrencyCode: "270",
    alphaCurrencyCode: "GMD",
    numericCurrencyCode: "270",
    minorUnit: "2",
  },

  {
    countryName: "Georgia",
    alpha2: "GE",
    alpha3: "GEO",
    numericContryCode: "268",
    currencyName: "Lari",
    defaultNumerucCurrencyCode: "981",
    alphaCurrencyCode: "GEL",
    numericCurrencyCode: "981",
    minorUnit: "2",
  },

  {
    countryName: "XX",
    alpha2: "X",
    alpha3: "X",
    numericContryCode: "X",
    currencyName: "XX",
    defaultNumerucCurrencyCode: "X",
    alphaCurrencyCode: "X",
    numericCurrencyCode: "X",
    minorUnit: "2",
  },

  {
    countryName: "Germany",
    alpha2: "DE",
    alpha3: "DEU",
    numericContryCode: "276",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Ghana",
    alpha2: "GH",
    alpha3: "GHA",
    numericContryCode: "288",
    currencyName: "Cedi",
    defaultNumerucCurrencyCode: "936",
    alphaCurrencyCode: "GHS",
    numericCurrencyCode: "936",
    minorUnit: "2",
  },

  {
    countryName: "Gibraltar",
    alpha2: "GI",
    alpha3: "GIB",
    numericContryCode: "292",
    currencyName: "Gibraltar Pound",
    defaultNumerucCurrencyCode: "292",
    alphaCurrencyCode: "GIP",
    numericCurrencyCode: "292",
    minorUnit: "2",
  },

  {
    countryName: "Greece",
    alpha2: "GR",
    alpha3: "GRC",
    numericContryCode: "300",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Greenland",
    alpha2: "GL",
    alpha3: "GRL",
    numericContryCode: "304",
    currencyName: "Danish Krone",
    defaultNumerucCurrencyCode: "208",
    alphaCurrencyCode: "DKK",
    numericCurrencyCode: "208",
    minorUnit: "2",
  },

  {
    countryName: "Grenada",
    alpha2: "GD",
    alpha3: "GRD",
    numericContryCode: "308",
    currencyName: "E. Caribbean Dollar",
    defaultNumerucCurrencyCode: "951",
    alphaCurrencyCode: "XCD",
    numericCurrencyCode: "951",
    minorUnit: "2",
  },

  {
    countryName: "Guadeloupe",
    alpha2: "GP",
    alpha3: "GLP",
    numericContryCode: "312",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Guam",
    alpha2: "GU",
    alpha3: "GUM",
    numericContryCode: "316",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Guatemala",
    alpha2: "GT",
    alpha3: "GTM",
    numericContryCode: "320",
    currencyName: "Quetzal",
    defaultNumerucCurrencyCode: "320",
    alphaCurrencyCode: "GTQ",
    numericCurrencyCode: "320",
    minorUnit: "2",
  },

  {
    countryName: "Guinea",
    alpha2: "GN",
    alpha3: "GIN",
    numericContryCode: "324",
    currencyName: "Guinea Franc",
    defaultNumerucCurrencyCode: "324",
    alphaCurrencyCode: "GNF",
    numericCurrencyCode: "324",
    minorUnit: "2",
  },

  {
    countryName: "Guinea-Bissau",
    alpha2: "GW",
    alpha3: "GNB",
    numericContryCode: "624",
    currencyName: "Guinea-Bissau Peso",
    defaultNumerucCurrencyCode: "624",
    alphaCurrencyCode: "GWP",
    numericCurrencyCode: "624",
    minorUnit: "2",
  },

  {
    countryName: "Guyana",
    alpha2: "GY",
    alpha3: "GUY",
    numericContryCode: "328",
    currencyName: "Guyana Dollar",
    defaultNumerucCurrencyCode: "328",
    alphaCurrencyCode: "GYD",
    numericCurrencyCode: "328",
    minorUnit: "2",
  },

  {
    countryName: "Haiti",
    alpha2: "HT",
    alpha3: "HTI",
    numericContryCode: "332",
    currencyName: "Gourde",
    defaultNumerucCurrencyCode: "332",
    alphaCurrencyCode: "HTG",
    numericCurrencyCode: "332",
    minorUnit: "2",
  },

  {
    countryName: "Heard and McDonald Is.",
    alpha2: "HM",
    alpha3: "HMD",
    numericContryCode: "334",
    currencyName: "Australian Dollar",
    defaultNumerucCurrencyCode: "036",
    alphaCurrencyCode: "AUD",
    numericCurrencyCode: "036",
    minorUnit: "2",
  },

  {
    countryName: "Holy See (Vatican City State)",
    alpha2: "VA",
    alpha3: "VAT",
    numericContryCode: "336",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Honduras",
    alpha2: "HN",
    alpha3: "HND",
    numericContryCode: "340",
    currencyName: "Lempira",
    defaultNumerucCurrencyCode: "340",
    alphaCurrencyCode: "HNL",
    numericCurrencyCode: "340",
    minorUnit: "2",
  },

  {
    countryName: "Hong Kong",
    alpha2: "HK",
    alpha3: "HKG",
    numericContryCode: "344",
    currencyName: "Hong Kong Dollar",
    defaultNumerucCurrencyCode: "344",
    alphaCurrencyCode: "HKD",
    numericCurrencyCode: "344",
    minorUnit: "2",
  },

  {
    countryName: "Hungary",
    alpha2: "HU",
    alpha3: "HUN",
    numericContryCode: "348",
    currencyName: "Forint",
    defaultNumerucCurrencyCode: "348",
    alphaCurrencyCode: "HUF",
    numericCurrencyCode: "348",
    minorUnit: "2",
  },

  {
    countryName: "Iceland",
    alpha2: "IS",
    alpha3: "ISL",
    numericContryCode: "352",
    currencyName: "Iceland Krona",
    defaultNumerucCurrencyCode: "352",
    alphaCurrencyCode: "ISK",
    numericCurrencyCode: "352",
    minorUnit: "2",
  },

  {
    countryName: "India",
    alpha2: "IN",
    alpha3: "IND",
    numericContryCode: "356",
    currencyName: "Indian Rupee",
    defaultNumerucCurrencyCode: "356",
    alphaCurrencyCode: "INR",
    numericCurrencyCode: "356",
    minorUnit: "2",
  },

  {
    countryName: "Indonesia",
    alpha2: "ID",
    alpha3: "IDN",
    numericContryCode: "360",
    currencyName: "Rupiah",
    defaultNumerucCurrencyCode: "360",
    alphaCurrencyCode: "IDR",
    numericCurrencyCode: "360",
    minorUnit: "2",
  },

  {
    countryName: "Iran",
    alpha2: "IR",
    alpha3: "IRN",
    numericContryCode: "364",
    currencyName: "Iranian Rial",
    defaultNumerucCurrencyCode: "364",
    alphaCurrencyCode: "IRR",
    numericCurrencyCode: "364",
    minorUnit: "2",
  },

  {
    countryName: "Iraq",
    alpha2: "IQ",
    alpha3: "IRQ",
    numericContryCode: "368",
    currencyName: "Iraqi Dinar",
    defaultNumerucCurrencyCode: "368",
    alphaCurrencyCode: "IQD",
    numericCurrencyCode: "368",
    minorUnit: "3",
  },

  {
    countryName: "Ireland",
    alpha2: "IE",
    alpha3: "IRL",
    numericContryCode: "372",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Isreal",
    alpha2: "IL",
    alpha3: "ISR",
    numericContryCode: "376",
    currencyName: "New Israeli Shequel",
    defaultNumerucCurrencyCode: "376",
    alphaCurrencyCode: "ILS",
    numericCurrencyCode: "376",
    minorUnit: "2",
  },

  {
    countryName: "Italy",
    alpha2: "IT",
    alpha3: "ITA",
    numericContryCode: "380",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Jamaica",
    alpha2: "JM",
    alpha3: "JAM",
    numericContryCode: "388",
    currencyName: "Jamaican Dollar",
    defaultNumerucCurrencyCode: "388",
    alphaCurrencyCode: "JMD",
    numericCurrencyCode: "388",
    minorUnit: "2",
  },

  {
    countryName: "Japan",
    alpha2: "JP",
    alpha3: "JPN",
    numericContryCode: "392",
    currencyName: "Yen",
    defaultNumerucCurrencyCode: "392",
    alphaCurrencyCode: "JPY",
    numericCurrencyCode: "392",
    minorUnit: "0",
  },

  {
    countryName: "Jordan",
    alpha2: "JO",
    alpha3: "JOR",
    numericContryCode: "400",
    currencyName: "Jordanian Dinar",
    defaultNumerucCurrencyCode: "400",
    alphaCurrencyCode: "JOD",
    numericCurrencyCode: "400",
    minorUnit: "3",
  },

  {
    countryName: "Kazakhstan",
    alpha2: "KZ",
    alpha3: "KAZ",
    numericContryCode: "398",
    currencyName: "Tenge",
    defaultNumerucCurrencyCode: "398",
    alphaCurrencyCode: "KZT",
    numericCurrencyCode: "398",
    minorUnit: "2",
  },

  {
    countryName: "Kenya",
    alpha2: "KE",
    alpha3: "KEN",
    numericContryCode: "404",
    currencyName: "Kenyan Shilling",
    defaultNumerucCurrencyCode: "404",
    alphaCurrencyCode: "KES",
    numericCurrencyCode: "404",
    minorUnit: "2",
  },

  {
    countryName: "Kiribati",
    alpha2: "KI",
    alpha3: "KIR",
    numericContryCode: "296",
    currencyName: "Australian Dollar",
    defaultNumerucCurrencyCode: "036",
    alphaCurrencyCode: "AUD",
    numericCurrencyCode: "036",
    minorUnit: "2",
  },

  {
    countryName: "Korea(North Korea)",
    alpha2: "KP",
    alpha3: "PRK",
    numericContryCode: "408",
    currencyName: "North Korean Won",
    defaultNumerucCurrencyCode: "408",
    alphaCurrencyCode: "KPW",
    numericCurrencyCode: "408",
    minorUnit: "2",
  },

  {
    countryName: "Korea",
    alpha2: "KR",
    alpha3: "KOR",
    numericContryCode: "410",
    currencyName: "Won",
    defaultNumerucCurrencyCode: "410",
    alphaCurrencyCode: "KRW",
    numericCurrencyCode: "410",
    minorUnit: "0",
  },

  {
    countryName: "Kuwait",
    alpha2: "KW",
    alpha3: "KWT",
    numericContryCode: "414",
    currencyName: "Kuwaiti Dinar",
    defaultNumerucCurrencyCode: "414",
    alphaCurrencyCode: "KWD",
    numericCurrencyCode: "414",
    minorUnit: "3",
  },

  {
    countryName: "Kyrgyzstan",
    alpha2: "KG",
    alpha3: "KGZ",
    numericContryCode: "417",
    currencyName: "Som",
    defaultNumerucCurrencyCode: "417",
    alphaCurrencyCode: "KGS",
    numericCurrencyCode: "417",
    minorUnit: "2",
  },

  {
    countryName: "Laos",
    alpha2: "LA",
    alpha3: "LAO",
    numericContryCode: "418",
    currencyName: "Kip",
    defaultNumerucCurrencyCode: "418",
    alphaCurrencyCode: "LAK",
    numericCurrencyCode: "418",
    minorUnit: "2",
  },

  {
    countryName: "Latvia",
    alpha2: "LV",
    alpha3: "LVA",
    numericContryCode: "428",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Lebanon",
    alpha2: "LB",
    alpha3: "LBN",
    numericContryCode: "422",
    currencyName: "Lebanese Pound",
    defaultNumerucCurrencyCode: "422",
    alphaCurrencyCode: "LBP",
    numericCurrencyCode: "422",
    minorUnit: "2",
  },

  {
    countryName: "Lesotho",
    alpha2: "LS",
    alpha3: "LSO",
    numericContryCode: "426",
    currencyName: "Lesotho Loti <br>Rand",
    defaultNumerucCurrencyCode: "426<br>710",
    alphaCurrencyCode: "LSL<br>ZAR",
    numericCurrencyCode: "426<br>710",
    minorUnit: "2<br>2",
  },

  {
    countryName: "Liberia",
    alpha2: "LR",
    alpha3: "LBR",
    numericContryCode: "430",
    currencyName: "Liberian Dollar",
    defaultNumerucCurrencyCode: "430",
    alphaCurrencyCode: "LRD",
    numericCurrencyCode: "430",
    minorUnit: "2",
  },

  {
    countryName: "Libyan Arab Jamahiriya",
    alpha2: "LY",
    alpha3: "LBY",
    numericContryCode: "434",
    currencyName: "Libyan Dinar",
    defaultNumerucCurrencyCode: "434",
    alphaCurrencyCode: "LYD",
    numericCurrencyCode: "434",
    minorUnit: "3",
  },

  {
    countryName: "Liechtenstein",
    alpha2: "LI",
    alpha3: "LIE",
    numericContryCode: "438",
    currencyName: "Swiss Franc",
    defaultNumerucCurrencyCode: "756",
    alphaCurrencyCode: "CHF",
    numericCurrencyCode: "756",
    minorUnit: "2",
  },

  {
    countryName: "Lithuania",
    alpha2: "LT",
    alpha3: "LTU",
    numericContryCode: "440",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Luxembourg",
    alpha2: "LU",
    alpha3: "LUX",
    numericContryCode: "442",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "Euro",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Macau",
    alpha2: "MO",
    alpha3: "MAC",
    numericContryCode: "446",
    currencyName: "Pataca",
    defaultNumerucCurrencyCode: "446",
    alphaCurrencyCode: "MOP",
    numericCurrencyCode: "446",
    minorUnit: "2",
  },

  {
    countryName: "Macedonia",
    alpha2: "MK",
    alpha3: "MKD",
    numericContryCode: "807",
    currencyName: "Denar",
    defaultNumerucCurrencyCode: "807",
    alphaCurrencyCode: "MKD",
    numericCurrencyCode: "807",
    minorUnit: "2",
  },

  {
    countryName: "Madagascar",
    alpha2: "MG",
    alpha3: "MDG",
    numericContryCode: "450",
    currencyName: "Malagasy Ariary",
    defaultNumerucCurrencyCode: "969",
    alphaCurrencyCode: "MGA",
    numericCurrencyCode: "969",
    minorUnit: "2",
  },

  {
    countryName: "Malawi",
    alpha2: "MW",
    alpha3: "MWI",
    numericContryCode: "454",
    currencyName: "Kwacha",
    defaultNumerucCurrencyCode: "454",
    alphaCurrencyCode: "MWK",
    numericCurrencyCode: "454",
    minorUnit: "2",
  },

  {
    countryName: "Malaysia",
    alpha2: "MY",
    alpha3: "MYS",
    numericContryCode: "458",
    currencyName: "Malaysian Ringgit",
    defaultNumerucCurrencyCode: "458",
    alphaCurrencyCode: "MYR",
    numericCurrencyCode: "458",
    minorUnit: "2",
  },

  {
    countryName: "Maldives",
    alpha2: "MV",
    alpha3: "MDV",
    numericContryCode: "462",
    currencyName: "Rufiyaa",
    defaultNumerucCurrencyCode: "462",
    alphaCurrencyCode: "MVR",
    numericCurrencyCode: "462",
    minorUnit: "2",
  },

  {
    countryName: "Mali",
    alpha2: "ML",
    alpha3: "MLI",
    numericContryCode: "466",
    currencyName: "CFA Franc BCEAO",
    defaultNumerucCurrencyCode: "952",
    alphaCurrencyCode: "XOF",
    numericCurrencyCode: "952",
    minorUnit: "0",
  },

  {
    countryName: "Malta",
    alpha2: "MT",
    alpha3: "MLT",
    numericContryCode: "470",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Marshall Islands",
    alpha2: "MH",
    alpha3: "MHL",
    numericContryCode: "584",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Martinique",
    alpha2: "MQ",
    alpha3: "MTQ",
    numericContryCode: "474",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Mauritania",
    alpha2: "MR",
    alpha3: "MRT",
    numericContryCode: "478",
    currencyName: "Ouguiya",
    defaultNumerucCurrencyCode: "478",
    alphaCurrencyCode: "MRO",
    numericCurrencyCode: "478",
    minorUnit: "2",
  },

  {
    countryName: "Mauritius",
    alpha2: "MU",
    alpha3: "MUS",
    numericContryCode: "480",
    currencyName: "Mauritius Rupee",
    defaultNumerucCurrencyCode: "480",
    alphaCurrencyCode: "MUR",
    numericCurrencyCode: "480",
    minorUnit: "2",
  },

  {
    countryName: "Mayotte",
    alpha2: "YT",
    alpha3: "MYT",
    numericContryCode: "175",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Mexico",
    alpha2: "MX",
    alpha3: "MEX",
    numericContryCode: "484",
    currencyName: "Mexican Peso",
    defaultNumerucCurrencyCode: "484",
    alphaCurrencyCode: "MXN",
    numericCurrencyCode: "484",
    minorUnit: "2",
  },

  {
    countryName: "Micronesia",
    alpha2: "FM",
    alpha3: "FSM",
    numericContryCode: "583",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Moldova",
    alpha2: "MD",
    alpha3: "MDA",
    numericContryCode: "498",
    currencyName: "Moldovan Leu",
    defaultNumerucCurrencyCode: "498",
    alphaCurrencyCode: "MDL",
    numericCurrencyCode: "498",
    minorUnit: "2",
  },

  {
    countryName: "Monaco",
    alpha2: "MC",
    alpha3: "MCO",
    numericContryCode: "492",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Mongolia",
    alpha2: "MN",
    alpha3: "MNG",
    numericContryCode: "496",
    currencyName: "Tugrik",
    defaultNumerucCurrencyCode: "496",
    alphaCurrencyCode: "MNT",
    numericCurrencyCode: "496",
    minorUnit: "2",
  },

  {
    countryName: "Montenegro",
    alpha2: "ME",
    alpha3: "MNE",
    numericContryCode: "499",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Montserrat",
    alpha2: "MS",
    alpha3: "MSR",
    numericContryCode: "500",
    currencyName: "E. Caribbean Dollar",
    defaultNumerucCurrencyCode: "951",
    alphaCurrencyCode: "XCD",
    numericCurrencyCode: "951",
    minorUnit: "2",
  },

  {
    countryName: "Morocco",
    alpha2: "MA",
    alpha3: "MAr",
    numericContryCode: "504",
    currencyName: "Moroccan Dirham",
    defaultNumerucCurrencyCode: "504",
    alphaCurrencyCode: "MAD",
    numericCurrencyCode: "504",
    minorUnit: "2",
  },

  {
    countryName: "Mozambique",
    alpha2: "MZ",
    alpha3: "MOZ",
    numericContryCode: "508",
    currencyName: "Mozambique Metical",
    defaultNumerucCurrencyCode: "943",
    alphaCurrencyCode: "MZN",
    numericCurrencyCode: "943",
    minorUnit: "2",
  },

  {
    countryName: "Myanmar",
    alpha2: "MM",
    alpha3: "MMR",
    numericContryCode: "104",
    currencyName: "Kyat",
    defaultNumerucCurrencyCode: "104",
    alphaCurrencyCode: "MMK",
    numericCurrencyCode: "104",
    minorUnit: "2",
  },

  {
    countryName: "Namibia",
    alpha2: "NA",
    alpha3: "NAM",
    numericContryCode: "516",
    currencyName: "Namibia Dollar<br>Rand",
    defaultNumerucCurrencyCode: "516<br>",
    alphaCurrencyCode: "NAD<br>ZAR",
    numericCurrencyCode: "516<br>710",
    minorUnit: "2",
  },

  {
    countryName: "Nauru",
    alpha2: "NR",
    alpha3: "NRU",
    numericContryCode: "520",
    currencyName: "Australian Dollar",
    defaultNumerucCurrencyCode: "036",
    alphaCurrencyCode: "AUD",
    numericCurrencyCode: "036",
    minorUnit: "2",
  },

  {
    countryName: "Nepal",
    alpha2: "NR",
    alpha3: "NPL",
    numericContryCode: "524",
    currencyName: "Nepalese Rupee",
    defaultNumerucCurrencyCode: "524",
    alphaCurrencyCode: "NPR",
    numericCurrencyCode: "524",
    minorUnit: "2",
  },

  {
    countryName: "Netherlands",
    alpha2: "NL",
    alpha3: "NLD",
    numericContryCode: "528",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Netherlands Antilles",
    alpha2: "AN",
    alpha3: "ANT",
    numericContryCode: "530",
    currencyName: "Netherlands Antillean Guilder",
    defaultNumerucCurrencyCode: "532",
    alphaCurrencyCode: "ANG",
    numericCurrencyCode: "532",
    minorUnit: "2",
  },

  {
    countryName: "New Caledonia",
    alpha2: "NC",
    alpha3: "NCL",
    numericContryCode: "540",
    currencyName: "CFP Franc",
    defaultNumerucCurrencyCode: "953",
    alphaCurrencyCode: "XPF",
    numericCurrencyCode: "953",
    minorUnit: "0",
  },

  {
    countryName: "New Zealand",
    alpha2: "NZ",
    alpha3: "NZL",
    numericContryCode: "554",
    currencyName: "New Zealand Dollar",
    defaultNumerucCurrencyCode: "554",
    alphaCurrencyCode: "NZD",
    numericCurrencyCode: "554",
    minorUnit: "2",
  },

  {
    countryName: "Nicaragua",
    alpha2: "NI",
    alpha3: "NIC",
    numericContryCode: "558",
    currencyName: "Cordoba Oro",
    defaultNumerucCurrencyCode: "558",
    alphaCurrencyCode: "NIO",
    numericCurrencyCode: "558",
    minorUnit: "2",
  },

  {
    countryName: "Niger",
    alpha2: "NE",
    alpha3: "NER",
    numericContryCode: "562",
    currencyName: "CFA Franc BCEAO",
    defaultNumerucCurrencyCode: "952",
    alphaCurrencyCode: "XOF",
    numericCurrencyCode: "952",
    minorUnit: "0",
  },

  {
    countryName: "Nigeria",
    alpha2: "NG",
    alpha3: "NGA",
    numericContryCode: "566",
    currencyName: "Naira",
    defaultNumerucCurrencyCode: "566",
    alphaCurrencyCode: "NGA",
    numericCurrencyCode: "566",
    minorUnit: "2",
  },

  {
    countryName: "Niue",
    alpha2: "NU",
    alpha3: "NIU",
    numericContryCode: "570",
    currencyName: "New Zealand Dollar",
    defaultNumerucCurrencyCode: "554",
    alphaCurrencyCode: "NZD",
    numericCurrencyCode: "554",
    minorUnit: "2",
  },

  {
    countryName: "Norfolk Is.",
    alpha2: "NF",
    alpha3: "NFK",
    numericContryCode: "574",
    currencyName: "Australian Dollar",
    defaultNumerucCurrencyCode: "036",
    alphaCurrencyCode: "AUD",
    numericCurrencyCode: "036",
    minorUnit: "2",
  },

  {
    countryName: "Northern Mariana Islands",
    alpha2: "MP",
    alpha3: "MNP",
    numericContryCode: "580",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Norway",
    alpha2: "NO",
    alpha3: "NOR",
    numericContryCode: "578",
    currencyName: "Norwegian Krone",
    defaultNumerucCurrencyCode: "578",
    alphaCurrencyCode: "NOK",
    numericCurrencyCode: "578",
    minorUnit: "2",
  },
  {
    countryName: "Oman",
    alpha2: "OM",
    alpha3: "OMN",
    numericContryCode: "512",
    currencyName: "Rial Omani",
    defaultNumerucCurrencyCode: "512",
    alphaCurrencyCode: "OMR",
    numericCurrencyCode: "512",
    minorUnit: "3",
  },

  {
    countryName: "Pakistan",
    alpha2: "PK",
    alpha3: "PAK",
    numericContryCode: "586",
    currencyName: "Pakistan Rupee",
    defaultNumerucCurrencyCode: "586",
    alphaCurrencyCode: "PKR",
    numericCurrencyCode: "586",
    minorUnit: "2",
  },
  {
    countryName: "Palau",
    alpha2: "PW",
    alpha3: "PLW",
    numericContryCode: "585",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Palestinian Territory",
    alpha2: "PS",
    alpha3: "PSE",
    numericContryCode: "275",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },
  {
    countryName: "Panama",
    alpha2: "PA",
    alpha3: "PAN",
    numericContryCode: "591",
    currencyName: "Balboa",
    defaultNumerucCurrencyCode: "590",
    alphaCurrencyCode: "PAB",
    numericCurrencyCode: "590",
    minorUnit: "2",
  },

  {
    countryName: "Papua New Guinea",
    alpha2: "PG",
    alpha3: "PNG",
    numericContryCode: "598",
    currencyName: "Kina",
    defaultNumerucCurrencyCode: "598",
    alphaCurrencyCode: "PGK",
    numericCurrencyCode: "598",
    minorUnit: "2",
  },
  {
    countryName: "Paraguay",
    alpha2: "PY",
    alpha3: "PRY",
    numericContryCode: "600",
    currencyName: "Guarani",
    defaultNumerucCurrencyCode: "600",
    alphaCurrencyCode: "PYG",
    numericCurrencyCode: "600",
    minorUnit: "0",
  },

  {
    countryName: "Peru",
    alpha2: "PE",
    alpha3: "PER",
    numericContryCode: "604",
    currencyName: "Nuevo Sol",
    defaultNumerucCurrencyCode: "604",
    alphaCurrencyCode: "PEN",
    numericCurrencyCode: "604",
    minorUnit: "2",
  },
  {
    countryName: "Philippines",
    alpha2: "PH",
    alpha3: "PHL",
    numericContryCode: "608",
    currencyName: "Philippine Peso",
    defaultNumerucCurrencyCode: "608",
    alphaCurrencyCode: "PHP",
    numericCurrencyCode: "608",
    minorUnit: "2",
  },

  {
    countryName: "Pitcairn",
    alpha2: "PN",
    alpha3: "PCN",
    numericContryCode: "612",
    currencyName: "New Zealand Dollar",
    defaultNumerucCurrencyCode: "554",
    alphaCurrencyCode: "NZD",
    numericCurrencyCode: "554",
    minorUnit: "2",
  },
  {
    countryName: "Poland",
    alpha2: "PL",
    alpha3: "POL",
    numericContryCode: "616",
    currencyName: "Zloty",
    defaultNumerucCurrencyCode: "985",
    alphaCurrencyCode: "PLN",
    numericCurrencyCode: "985",
    minorUnit: "2",
  },

  {
    countryName: "Portugal",
    alpha2: "PT",
    alpha3: "PRT",
    numericContryCode: "620",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },
  {
    countryName: "Puerto Rico",
    alpha2: "PR",
    alpha3: "PRI",
    numericContryCode: "630",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Qatar",
    alpha2: "QA",
    alpha3: "QAT",
    numericContryCode: "634",
    currencyName: "Qatari Rial",
    defaultNumerucCurrencyCode: "634",
    alphaCurrencyCode: "QAR",
    numericCurrencyCode: "634",
    minorUnit: "2",
  },
  {
    countryName: "Reunion",
    alpha2: "RE",
    alpha3: "REU",
    numericContryCode: "638",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Romania",
    alpha2: "RO",
    alpha3: "ROM",
    numericContryCode: "642",
    currencyName: "Leu",
    defaultNumerucCurrencyCode: "946",
    alphaCurrencyCode: "RON",
    numericCurrencyCode: "946",
    minorUnit: "2",
  },
  {
    countryName: "Russian Federation",
    alpha2: "RU",
    alpha3: "RUS",
    numericContryCode: "643",
    currencyName: "Russian Ruble",
    defaultNumerucCurrencyCode: "643",
    alphaCurrencyCode: "RUB",
    numericCurrencyCode: "643",
    minorUnit: "2",
  },

  {
    countryName: "Rwanda",
    alpha2: "RW",
    alpha3: "RWA",
    numericContryCode: "646",
    currencyName: "Rwanda Franc",
    defaultNumerucCurrencyCode: "646",
    alphaCurrencyCode: "RWF",
    numericCurrencyCode: "646",
    minorUnit: "0",
  },
  {
    countryName: "Samoa",
    alpha2: "WS",
    alpha3: "WSM",
    numericContryCode: "882",
    currencyName: "Tala",
    defaultNumerucCurrencyCode: "882",
    alphaCurrencyCode: "WST",
    numericCurrencyCode: "882",
    minorUnit: "2",
  },

  {
    countryName: "San Marino",
    alpha2: "SM",
    alpha3: "SMR",
    numericContryCode: "674",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },
  {
    countryName: "Sao Tome and Principe",
    alpha2: "ST",
    alpha3: "STP",
    numericContryCode: "678",
    currencyName: "Dobra",
    defaultNumerucCurrencyCode: "678",
    alphaCurrencyCode: "STD",
    numericCurrencyCode: "678",
    minorUnit: "2",
  },

  {
    countryName: "Saudi Arabia",
    alpha2: "SA",
    alpha3: "SAU",
    numericContryCode: "682",
    currencyName: "Saudi Riyal",
    defaultNumerucCurrencyCode: "682",
    alphaCurrencyCode: "SAR",
    numericCurrencyCode: "682",
    minorUnit: "2",
  },
  {
    countryName: "Senegal",
    alpha2: "SN",
    alpha3: "SEN",
    numericContryCode: "686",
    currencyName: "CFA Franc BCEAO",
    defaultNumerucCurrencyCode: "952",
    alphaCurrencyCode: "XOF",
    numericCurrencyCode: "952",
    minorUnit: "0",
  },

  {
    countryName: "Serbia",
    alpha2: "RS",
    alpha3: "SRB",
    numericContryCode: "688",
    currencyName: "Serbian Dinar",
    defaultNumerucCurrencyCode: "941",
    alphaCurrencyCode: "RSD",
    numericCurrencyCode: "941",
    minorUnit: "2",
  },
  {
    countryName: "Seychelles",
    alpha2: "SC",
    alpha3: "SYC",
    numericContryCode: "690",
    currencyName: "Seychelles Rupee",
    defaultNumerucCurrencyCode: "690",
    alphaCurrencyCode: "SCR",
    numericCurrencyCode: "690",
    minorUnit: "2",
  },

  {
    countryName: "Sierra Leone",
    alpha2: "SL",
    alpha3: "SLE",
    numericContryCode: "694",
    currencyName: "Leone",
    defaultNumerucCurrencyCode: "694",
    alphaCurrencyCode: "SLL",
    numericCurrencyCode: "694",
    minorUnit: "2",
  },
  {
    countryName: "Singapore",
    alpha2: "SG",
    alpha3: "SGP",
    numericContryCode: "702",
    currencyName: "Singapore Dollar",
    defaultNumerucCurrencyCode: "702",
    alphaCurrencyCode: "SGD",
    numericCurrencyCode: "702",
    minorUnit: "2",
  },

  {
    countryName: "Slovakia",
    alpha2: "SK",
    alpha3: "SVK",
    numericContryCode: "703",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },
  {
    countryName: "Slovenia",
    alpha2: "SI",
    alpha3: "SVN",
    numericContryCode: "705",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },

  {
    countryName: "Solomon Is.",
    alpha2: "SB",
    alpha3: "SLB",
    numericContryCode: "090",
    currencyName: "Solomon Is. Dollar",
    defaultNumerucCurrencyCode: "090",
    alphaCurrencyCode: "SBD",
    numericCurrencyCode: "090",
    minorUnit: "2",
  },
  {
    countryName: "Somalia",
    alpha2: "SO",
    alpha3: "SOM",
    numericContryCode: "706",
    currencyName: "Somali Shilling",
    defaultNumerucCurrencyCode: "706",
    alphaCurrencyCode: "SOS",
    numericCurrencyCode: "706",
    minorUnit: "2",
  },

  {
    countryName: "South Africa",
    alpha2: "ZA",
    alpha3: "ZAF",
    numericContryCode: "710",
    currencyName: "Rand",
    defaultNumerucCurrencyCode: "710",
    alphaCurrencyCode: "ZAF",
    numericCurrencyCode: "710",
    minorUnit: "2",
  },
  {
    countryName: "So. Georgia and So. Sandwich Is.",
    alpha2: "GS",
    alpha3: "SGS",
    numericContryCode: "239",
    currencyName: "Pound Sterling",
    defaultNumerucCurrencyCode: "826",
    alphaCurrencyCode: "GBP",
    numericCurrencyCode: "826",
    minorUnit: "2",
  },

  {
    countryName: "Spain",
    alpha2: "ES",
    alpha3: "ESP",
    numericContryCode: "724",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },
  {
    countryName: "Sri Lanka",
    alpha2: "LK",
    alpha3: "LKA",
    numericContryCode: "144",
    currencyName: "Sri Lanka Rupee",
    defaultNumerucCurrencyCode: "144",
    alphaCurrencyCode: "LKR",
    numericCurrencyCode: "144",
    minorUnit: "2",
  },

  {
    countryName: "St. Helena",
    alpha2: "SH",
    alpha3: "SHN",
    numericContryCode: "654",
    currencyName: "St. Helena Pound",
    defaultNumerucCurrencyCode: "654",
    alphaCurrencyCode: "SHP",
    numericCurrencyCode: "654",
    minorUnit: "2",
  },
  {
    countryName: "St. Kitts-Nevis",
    alpha2: "KN",
    alpha3: "KNA",
    numericContryCode: "659",
    currencyName: "E. Caribbean Dollar",
    defaultNumerucCurrencyCode: "951",
    alphaCurrencyCode: "XCD",
    numericCurrencyCode: "951",
    minorUnit: "2",
  },

  {
    countryName: "St. Lucia",
    alpha2: "LC",
    alpha3: "LCA",
    numericContryCode: "662",
    currencyName: "E. Caribbean Dollar",
    defaultNumerucCurrencyCode: "951",
    alphaCurrencyCode: "XCD",
    numericCurrencyCode: "951",
    minorUnit: "2",
  },
  {
    countryName: "St Maarten",
    alpha2: "SX",
    alpha3: "SXM",
    numericContryCode: "534",
    currencyName: "Netherlands Antillean Guilder",
    defaultNumerucCurrencyCode: "532",
    alphaCurrencyCode: "ANG",
    numericCurrencyCode: "532",
    minorUnit: "2",
  },

  {
    countryName: "St. Pierre and Miquelon",
    alpha2: "PM",
    alpha3: "SPM",
    numericContryCode: "666",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },
  {
    countryName: "St. Vincent and The Grenadines",
    alpha2: "VC",
    alpha3: "VCT",
    numericContryCode: "670",
    currencyName: "E. Caribbean Dollar",
    defaultNumerucCurrencyCode: "951",
    alphaCurrencyCode: "XCD",
    numericCurrencyCode: "951",
    minorUnit: "2",
  },

  {
    countryName: "Sudan",
    alpha2: "SD",
    alpha3: "SDN",
    numericContryCode: "729",
    currencyName: "Sudanese Pound",
    defaultNumerucCurrencyCode: "938",
    alphaCurrencyCode: "SDG",
    numericCurrencyCode: "938",
    minorUnit: "2",
  },
  {
    countryName: "South Sudan",
    alpha2: "SS",
    alpha3: "SSD",
    numericContryCode: "728",
    currencyName: "South Sudanese Pound",
    defaultNumerucCurrencyCode: "728",
    alphaCurrencyCode: "SSP",
    numericCurrencyCode: "728",
    minorUnit: "2",
  },

  {
    countryName: "Suriname",
    alpha2: "SR",
    alpha3: "SUR",
    numericContryCode: "740",
    currencyName: "Surinam Dollar",
    defaultNumerucCurrencyCode: "968",
    alphaCurrencyCode: "SRD",
    numericCurrencyCode: "968",
    minorUnit: "2",
  },
  {
    countryName: "Svalbard and Jan Mayen Is.",
    alpha2: "SJ",
    alpha3: "SJM",
    numericContryCode: "744",
    currencyName: "Norwegian Krone",
    defaultNumerucCurrencyCode: "578",
    alphaCurrencyCode: "NOK",
    numericCurrencyCode: "578",
    minorUnit: "2",
  },

  {
    countryName: "Swaziland",
    alpha2: "SZ",
    alpha3: "SWZ",
    numericContryCode: "748",
    currencyName: "Lilangeni",
    defaultNumerucCurrencyCode: "748",
    alphaCurrencyCode: "SZL",
    numericCurrencyCode: "748",
    minorUnit: "2",
  },
  {
    countryName: "Sweden",
    alpha2: "SE",
    alpha3: "SWE",
    numericContryCode: "752",
    currencyName: "Swedish Krona",
    defaultNumerucCurrencyCode: "752",
    alphaCurrencyCode: "SEK",
    numericCurrencyCode: "752",
    minorUnit: "2",
  },

  {
    countryName: "Switzerland",
    alpha2: "CH",
    alpha3: "CHE",
    numericContryCode: "756",
    currencyName: "Swiss Franc",
    defaultNumerucCurrencyCode: "756",
    alphaCurrencyCode: "CHF",
    numericCurrencyCode: "756",
    minorUnit: "2",
  },
  {
    countryName: "Syrian Arab Rep.",
    alpha2: "SY",
    alpha3: "SYR",
    numericContryCode: "760",
    currencyName: "Syrian Pound",
    defaultNumerucCurrencyCode: "760",
    alphaCurrencyCode: "SYP",
    numericCurrencyCode: "760",
    minorUnit: "2",
  },

  {
    countryName: "Taiwan",
    alpha2: "TW",
    alpha3: "TWN",
    numericContryCode: "158",
    currencyName: "New Taiwan Dollar",
    defaultNumerucCurrencyCode: "901",
    alphaCurrencyCode: "TWD",
    numericCurrencyCode: "901",
    minorUnit: "2",
  },
  {
    countryName: "Tajikistan",
    alpha2: "TJ",
    alpha3: "TJK",
    numericContryCode: "762",
    currencyName: "Somoni",
    defaultNumerucCurrencyCode: "972",
    alphaCurrencyCode: "TJS",
    numericCurrencyCode: "972",
    minorUnit: "2",
  },

  {
    countryName: "Tanzania",
    alpha2: "TZ",
    alpha3: "TZA",
    numericContryCode: "834",
    currencyName: "Tanzanian Shilling",
    defaultNumerucCurrencyCode: "834",
    alphaCurrencyCode: "TZS",
    numericCurrencyCode: "834",
    minorUnit: "2",
  },
  {
    countryName: "Thailand",
    alpha2: "TH",
    alpha3: "THA",
    numericContryCode: "764",
    currencyName: "Baht",
    defaultNumerucCurrencyCode: "764",
    alphaCurrencyCode: "THB",
    numericCurrencyCode: "764",
    minorUnit: "2",
  },

  {
    countryName: "Timor-Leste",
    alpha2: "TL",
    alpha3: "TLS",
    numericContryCode: "626",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },
  {
    countryName: "Togo",
    alpha2: "TG",
    alpha3: "TGO",
    numericContryCode: "768",
    currencyName: "CFA Franc BCEAO",
    defaultNumerucCurrencyCode: "952",
    alphaCurrencyCode: "XOF",
    numericCurrencyCode: "952",
    minorUnit: "0",
  },

  {
    countryName: "Tokelau",
    alpha2: "TK",
    alpha3: "TKL",
    numericContryCode: "772",
    currencyName: "New Zealand Dollar",
    defaultNumerucCurrencyCode: "554",
    alphaCurrencyCode: "NZD",
    numericCurrencyCode: "554",
    minorUnit: "2",
  },
  {
    countryName: "Tonga",
    alpha2: "TO",
    alpha3: "TON",
    numericContryCode: "776",
    currencyName: "Pa'anga",
    defaultNumerucCurrencyCode: "776",
    alphaCurrencyCode: "TOP",
    numericCurrencyCode: "776",
    minorUnit: "2",
  },

  {
    countryName: "Trinidad and Tobago",
    alpha2: "TT",
    alpha3: "TTO",
    numericContryCode: "780",
    currencyName: "Trinidad and Tobago Dollar",
    defaultNumerucCurrencyCode: "780",
    alphaCurrencyCode: "TTD",
    numericCurrencyCode: "780",
    minorUnit: "2",
  },
  {
    countryName: "Tunisia",
    alpha2: "TN",
    alpha3: "TUN",
    numericContryCode: "788",
    currencyName: "Tunisian Dinar",
    defaultNumerucCurrencyCode: "788",
    alphaCurrencyCode: "TND",
    numericCurrencyCode: "788",
    minorUnit: "3",
  },

  {
    countryName: "Turkey",
    alpha2: "TR",
    alpha3: "TUR",
    numericContryCode: "792",
    currencyName: "Turkish Lira",
    defaultNumerucCurrencyCode: "949",
    alphaCurrencyCode: "TRY",
    numericCurrencyCode: "949",
    minorUnit: "2",
  },
  {
    countryName: "Turkmenistan",
    alpha2: "TM",
    alpha3: "TKM",
    numericContryCode: "795",
    currencyName: "Manat",
    defaultNumerucCurrencyCode: "934",
    alphaCurrencyCode: "TMT",
    numericCurrencyCode: "934",
    minorUnit: "2",
  },

  {
    countryName: "Turks and Caicos Is.",
    alpha2: "TC",
    alpha3: "TCA",
    numericContryCode: "796",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },
  {
    countryName: "Tuvalu",
    alpha2: "TV",
    alpha3: "TUV",
    numericContryCode: "798",
    currencyName: "Australian Dollar",
    defaultNumerucCurrencyCode: "036",
    alphaCurrencyCode: "AUD",
    numericCurrencyCode: "036",
    minorUnit: "2",
  },

  {
    countryName: "Uganda",
    alpha2: "UG",
    alpha3: "UGA",
    numericContryCode: "800",
    currencyName: "Uganda Shilling",
    defaultNumerucCurrencyCode: "800",
    alphaCurrencyCode: "UGX",
    numericCurrencyCode: "800",
    minorUnit: "2",
  },
  {
    countryName: "Ukraine",
    alpha2: "UA",
    alpha3: "UKR",
    numericContryCode: "804",
    currencyName: "Ukrainian Hryvnia",
    defaultNumerucCurrencyCode: "980",
    alphaCurrencyCode: "UAH",
    numericCurrencyCode: "980",
    minorUnit: "2",
  },

  {
    countryName: "United Arab Emirates",
    alpha2: "AE",
    alpha3: "ARE",
    numericContryCode: "784",
    currencyName: "U.A.E. Dirham",
    defaultNumerucCurrencyCode: "784",
    alphaCurrencyCode: "AED",
    numericCurrencyCode: "784",
    minorUnit: "2",
  },
  {
    countryName: "United Kingdom",
    alpha2: "GB",
    alpha3: "GBR",
    numericContryCode: "826",
    currencyName: "Pound Sterling",
    defaultNumerucCurrencyCode: "826",
    alphaCurrencyCode: "GBP",
    numericCurrencyCode: "826",
    minorUnit: "2",
  },

  {
    countryName: "United Nations Interim Administration Mission in Kosovo",
    alpha2: "QZ",
    alpha3: "QZZ",
    numericContryCode: "900",
    currencyName: "Euro",
    defaultNumerucCurrencyCode: "978",
    alphaCurrencyCode: "EUR",
    numericCurrencyCode: "978",
    minorUnit: "2",
  },
  {
    countryName: "United States",
    alpha2: "US",
    alpha3: "USA",
    numericContryCode: "840",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "US Minor Outlying Islands",
    alpha2: "UM",
    alpha3: "UMI",
    numericContryCode: "581",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },
  {
    countryName: "US Virgin Is.",
    alpha2: "VI",
    alpha3: "VIR",
    numericContryCode: "850",
    currencyName: "US Dollar",
    defaultNumerucCurrencyCode: "840",
    alphaCurrencyCode: "USD",
    numericCurrencyCode: "840",
    minorUnit: "2",
  },

  {
    countryName: "Uruguay",
    alpha2: "UY",
    alpha3: "URY",
    numericContryCode: "858",
    currencyName: "Peso Uruguayo",
    defaultNumerucCurrencyCode: "858",
    alphaCurrencyCode: "UYU",
    numericCurrencyCode: "858",
    minorUnit: "2",
  },
  {
    countryName: "Uzbekistan",
    alpha2: "UZ",
    alpha3: "UZB",
    numericContryCode: "860",
    currencyName: "Uzbekistan Sum",
    defaultNumerucCurrencyCode: "860",
    alphaCurrencyCode: "UZS",
    numericCurrencyCode: "860",
    minorUnit: "2",
  },

  {
    countryName: "Vanuatu",
    alpha2: "VU",
    alpha3: "VUT",
    numericContryCode: "548",
    currencyName: "Vatu",
    defaultNumerucCurrencyCode: "548",
    alphaCurrencyCode: "VUV",
    numericCurrencyCode: "548",
    minorUnit: "0",
  },
  {
    countryName: "Venezuela",
    alpha2: "VE",
    alpha3: "VEN",
    numericContryCode: "862",
    currencyName: "Bolivar Fuerte",
    defaultNumerucCurrencyCode: "937",
    alphaCurrencyCode: "VEF",
    numericCurrencyCode: "937",
    minorUnit: "2",
  },

  {
    countryName: "Vietnam",
    alpha2: "VN",
    alpha3: "VNM",
    numericContryCode: "704",
    currencyName: "Dong",
    defaultNumerucCurrencyCode: "704",
    alphaCurrencyCode: "VND",
    numericCurrencyCode: "704",
    minorUnit: "0",
  },
  {
    countryName: "Wallis and Futuna Is.",
    alpha2: "WF",
    alpha3: "WLF",
    numericContryCode: "876",
    currencyName: "CFP Franc",
    defaultNumerucCurrencyCode: "953",
    alphaCurrencyCode: "XPF",
    numericCurrencyCode: "953",
    minorUnit: "0",
  },

  {
    countryName: "Western Sahara",
    alpha2: "EH",
    alpha3: "ESH",
    numericContryCode: "732",
    currencyName: "Moroccan Dirham",
    defaultNumerucCurrencyCode: "504",
    alphaCurrencyCode: "MAD",
    numericCurrencyCode: "504",
    minorUnit: "2",
  },
  {
    countryName: "Yemen",
    alpha2: "YE",
    alpha3: "YEM",
    numericContryCode: "887",
    currencyName: "Yemeni Rial",
    defaultNumerucCurrencyCode: "886",
    alphaCurrencyCode: "YER",
    numericCurrencyCode: "886",
    minorUnit: "2",
  },
  {
    countryName: "Zambia",
    alpha2: "ZM",
    alpha3: "ZMB",
    numericContryCode: "894",
    currencyName: "Zambian Kwacha",
    defaultNumerucCurrencyCode: "967",
    alphaCurrencyCode: "ZMW",
    numericCurrencyCode: "967",
    minorUnit: "2",
  },
  {
    countryName: "Zimbabwe",
    alpha2: "ZW",
    alpha3: "ZWE",
    numericContryCode: "716",
    currencyName: "Zimbabwe Dollar",
    defaultNumerucCurrencyCode: "716",
    alphaCurrencyCode: "ZWD",
    numericCurrencyCode: "716",
    minorUnit: "2",
  },
];
export default countriesCodes;
